name: Upload Documentation

on:
  push:
    branches: [master]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          toolchain: nightly

      - name: Build Docs
        run: cargo doc --workspace --all-features --no-deps

      - name: Tweak HTML
        run:
          echo '<meta http-equiv="refresh" content="0;url=actix/index.html">' >
          target/doc/index.html

      # TODO(JohnTitor): deploy via GHA directly instead.
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: target/doc
